title: Mokbel Karam
description: A minimal website for writing and note-taking.
author: Mokbel Karam
avatar: /logo.png
email: karammokbel@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: mokbelkaram
  card: summary
logo: logo.png
social:
  name: Mokbel Karam
  links:
    - https://twitter.com/mokbelkaram
    - https://github.com/mk-95
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
subscribe: false